language: ruby
sudo: required
dist: trusty
services:
- docker
node_js:
- node
addons:
  apt:
    config:
      retries: true
rvm:
- 2.4.0
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
script:
- bundle exec rake ci:tests
- docker build -t machinery-maintenance .
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: develop
notifications:
  email: false
env:
  global:
    secure: WjW78vcKiGsfGdYJ3Vu+g4C54MDNrR8IbmxCAyTMp+RgRXdMPCqWuw9Pnl4Xv+IK/Q1tK/HOaLGUvDmJ2ejt/hDgns2WatoqmNEtDC2xsAE4RiYab1/wPTpm9m7agyAfeT9i193ec8lVTT8HYl+c9YowYVwTodXLqxcN03gBeR5yK4p4BpKyOVP0DaDkFmTlaQea3UfFkpIquOKLKiX+tH7xCqot893kFJ2YQ3nI39Bzq/zTmt5N5ai5ywHbuZMEbL9v8UC2jnOvxw+3dubPlStKVt/gRVQZclhDoojmI4+L00fuGr/odZZ+pg1qocNDMaD4G9rhlN3FcNgKZErh+sP8vzi62Qc5errQx+1eCH9u+KEdo0NEzWvDhOZKHJIyTW/ETzU2NwsbySY47pCSymyAfOxxZJdmAt2IX4vYEAIQ5cC/N1EtTffsTsagKGkCs8YTOuPqNlxvvqvi1DyyfFlrJ+l8k818HxrQtJSWlHA1Je8iFv5lDKMJ8Xi5R0a4eRCfCnbE+/qMgLGW3dL8kblkDjx215mMyXpBAt/qqbjiPTveSJQ/+OtbXYlFeoR2nwFQUmkNwRvvmhbpGib1oFdV00QoQdIhWdlSMHVzlpaFpf4DCC8YdMseuOIA/UjPpQebetx0nB2WKIJs5mUq7BHNZKy2nI0AIzv7kf9PXLo=
