language: ruby
sudo: required
dist: trusty
services:
  - docker
node_js:
  - "node"
addons:
  apt:
    config:
      retries: true
rvm:
- 2.4.0
# before_install: # if "install" is overridden
#   # Repo for Yarn
#   - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
#   - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
#   - sudo apt-get update -qq
#   - sudo apt-get install -y -qq yarn
# cache:
#   yarn: true
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
script:
- bundle exec rake ci:tests
- docker build -t machinery-maintenance .
after_success:
- 
notifications:
  email: false
  
